# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJM06LhePRvKxm8NljgX207HSilCmTIC
"""

#exercise 1
# author cm
# state : ongoing

#exercise 2
#author NN
#state: ongoing

#exercise 3
#author AF
#state: ongoing